version: '3.8'
services:
  postgres-db:
    image: 'postgres:latest'
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: rafaela
      POSTGRES_PASSWORD: rafa123
      POSTGRES_DB: lojaCarro
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
volumes:
  pgdata: null
